# -*- coding: utf-8 -*-
"""Barlow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdUChP7xkB7S_ZGyf8F9YkmnTYgAF9VV

**Implementing Barlow's formula**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile barlows_formula.py
# def barlows_formula(pressure: float, diameter: float, thickness: float) -> float:
#     """
#     Calculates the hoop stress using Barlow's formula.
# 
#     Barlow's formula: S = (P * D) / (2 * t)
# 
#     Args:
#         pressure (float): Internal pressure (P) in psi.
#         diameter (float): Outer diameter (D) in inches.
#         thickness (float): Nominal wall thickness (t) in inches.
# 
#     Returns:
#         float: Hoop stress (S) in psi.
# 
#     Raises:
#         ValueError: If inputs are invalid (non-numeric, negative, or zero thickness).
#     """
# 
# 
#     # Input  Validation
#     if not all(isinstance(arg, (int, float)) for arg in [pressure, diameter, thickness]):
#         raise ValueError("All inputs (pressure, diameter, thickness) must be numeric.")
# 
#     if pressure < 0:
#         raise ValueError("Internal pressure (P) cannot be negative.")
# 
# 
#     if diameter <= 0:
#         raise ValueError("Outer diameter (D) must be positive.")
# 
# 
#     if thickness <= 0:
#         raise ValueError("Nominal wall thickness (t) must be positive and non-zero.")
# 
# 
#     # Calculate hoop stress
#     hoop_stress = (pressure * diameter) / (2 * thickness)
#     return hoop_stress
# 
# 
# """ TEST CASES"""
# if __name__ == "__main__":
#     print("--- Barlow's Formula Test Cases ---\n")
# 
# 
#     # TestCase 1: Valid positive inputs
#     try:
#         s1 = barlows_formula(pressure=1000, diameter=10, thickness=0.5)
#         print(f"TestCase 1 (Valid): P=1000 psi, D=10 in, t=0.5 in => Hoop Stress = {s1:.2f} psi")
#         assert abs(s1 - 10000.0) < 0.01
#     except ValueError as e:
#         print(f"TestCase 1 (Valid) FAILED: {e}")
# 
# 
#     # TestCase 2: Different valid positive inputs
#     try:
#         s2 = barlows_formula(pressure=200, diameter=24, thickness=1.0)
#         print(f"TestCase 2 (Valid): P=200 psi, D=24 in, t=1.0 in => Hoop Stress = {s2:.2f} psi")
#         assert abs(s2 - 2400.0) < 0.01
#     except ValueError as e:
#         print(f"TestCase 2 (Valid) FAILED: {e}")
# 
# 
#     # TestCase 3: Zero pressure (should be valid, stress will be zero)
#     try:
#         s3 = barlows_formula(pressure=0, diameter=12, thickness=0.25)
#         print(f"TestCase 3 (Valid): P=0 psi, D=12 in, t=0.25 in => Hoop Stress = {s3:.2f} psi")
#         assert abs(s3 - 0.0) < 0.01
#     except ValueError as e:
#         print(f"TestCase 3 (Valid) FAILED: {e}")
# 
# 
# 
#     # TestCase 4: Negative pressure (invalid)
#     try:
#         barlows_formula(pressure=-100, diameter=10, thickness=0.5)
#         print("TestCase 4 (Negative Pressure) FAILED: Expected ValueError.")
#     except ValueError as e:
#         print(f"TestCase 4 (Negative Pressure) PASSED: {e}")
# 
# 
#     # TestCase 5: Zero thickness (invalid)
#     try:
#         barlows_formula(pressure=1000, diameter=10, thickness=0)
#         print("TestCase 5 (Zero Thickness) FAILED: Expected ValueError.")
#     except ValueError as e:
#         print(f"TestCase 5 (Zero Thickness) PASSED: {e}")
# 
# 
#     # TestCase 6: Negative diameter (invalid)
#     try:
#         barlows_formula(pressure=1000, diameter=-10, thickness=0.5)
#         print("TestCase 6 (Negative Diameter) FAILED: Expected ValueError.")
#     except ValueError as e:
#         print(f"TestCase 6 (Negative Diameter) PASSED: {e}")
# 
# 
#     # TestCase 7: Non-numeric input for pressure (invalid)
#     try:
#         barlows_formula(pressure="abc", diameter=10, thickness=0.5)
#         print("TestCase 7 (Non-numeric Pressure) FAILED: Expected ValueError.")
#     except ValueError as e:
#         print(f"TestCase 7 (Non-numeric Pressure) PASSED: {e}")
# 
# 
#