# -*- coding: utf-8 -*-
"""UNIT_CONVERTER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BI6GKWKBIO94RMxBSvJSOz_TsMcflNu6

**UNIT CONVERSION LIBRARY**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile unit_conversion.csv
# """ Unit Conversion """
# #Pressure Conversion
# def psi_to_mpa(pressure_psi: float) -> float:
#       """ Convert pressure from psi to MPa."""
#       if pressure_psi < 0:
#         raise ValueError("Pressure cannot be negative.")
#       else:
#           return pressure_psi * 0.00689476
# 
# 
# def mpa_to_psi(pressure_mpa: float) -> float:
#     """Convert pressure from MPa to psi."""
#     return pressure_mpa / 0.00689476
# 
#  #Length Conversion
# def inches_to_mm(length_in: float) -> float:
#   """Convert length from inches to millimeters."""
#   if length_in < 0:
#     raise ValueError("Length cannot be negative.")
#   else:
#     return length_in * 25.4
# 
# def metres_to_feet(length_m: float) -> float:
#     """Convert length from metres to feet."""
#     if length_m < 0:
#         raise ValueError("Length cannot be negative.")
#     return length_m * 3.28084
# 
# 
# #Temperature Conversion
# def celsius_to_fahrenheit(temp_c: float) -> float:
#     """Convert temperature from Celsius to Fahrenheit."""
#     if temp_c < -273.15:
#         raise ValueError("Temperature cannot be below absolute zero (-273.15°C).")
#     return (temp_c * 9/5) + 32
# 
# def fahrenheit_to_celsius(temp_f: float) -> float:
#         """Convert temperature from Fahrenheit to Celsius."""
#         if temp_f < -459.67:
#             raise ValueError("Temperature cannot be below absolute zero (-459.67°F).")
#         return (temp_f - 32) * 5/9
# 
# 
#     #Force Conversion
# def lbf_to_newtons(force_lbf: float) -> float:
#     """Convert force from pounds-force (lbf) to Newtons (N)."""
#     if force_lbf < 0:
#         raise ValueError("Force cannot be negative.")
#     return force_lbf * 4.44822
# 
# def newtons_to_lbf(force_n: float) -> float:
#     """Convert force from Newtons (N) to pounds-force (lbf)."""
#     if force_n < 0:
#         raise ValueError("Force cannot be negative.")
#     return force_n / 4.44822
# 
# #Area Conversion
# def sq_feet_to_sq_meters(area_sq_ft: float) -> float:
#     """Convert area from square feet to square meters."""
#     if area_sq_ft < 0:
#         raise ValueError("Area cannot be negative.")
#     return area_sq_ft * 0.092903
# 
# def sq_meters_to_sq_feet(area_sq_m: float) -> float:
#         """Convert area from square meters to square feet."""
#         if area_sq_m < 0:
#             raise ValueError("Area cannot be negative.")
#         return area_sq_m * 10.7639
# 
# #Volume Conversion
# def cubic_meters_to_cubic_feet(volume_cu_m: float) -> float:
#       """ Convert volume from cubic meters to cubic feet."""
#       if volume_cu_m < 0:
#         raise ValueError("Volume cannot be negative.")
#       return volume_cu_m * 35.3147
# 
# def cubic_feet_to_cubic_meters(volume_cu_ft: float) -> float:
#       """Convert volume from cubic feet to cubic meters."""
#       if volume_cu_ft < 0:
#           raise ValueError("Volume cannot be negative.")
#       return volume_cu_ft / 35.3147
# 
# #Mass Conversion
# def kg_to_pounds(mass_kg: float) -> float:
#     """Convert mass from kilograms to pounds."""
#     if mass_kg < 0:
#         raise ValueError("Mass cannot be negative.")
#     return mass_kg * 2.20462
# 
# def pounds_to_kg(mass_lbs: float) -> float:
#     """Convert mass from pounds to kilograms."""
#     if mass_lbs < 0:
#         raise ValueError("Mass cannot be negative.")
#     return mass_lbs / 2.20462
# 
# 
# #Flow rate Conversion
# def cms_to_cfs(flowrate_cms: float) -> float:
#     """Convert flowrate from cubic meters per second (cms) to cubic feet per second (cfs)."""
#     if flowrate_cms < 0:
#         raise ValueError("Flow rate cannot be negative.")
#     return flowrate_cms * 35.3147
# 
# def cfs_to_cms(flowrate_cfs: float) -> float:
#         """Convert flowrate from cubic feet per second (cfs) to cubic meters per second (cms)."""
#         if flowrate_cfs < 0:
#             raise ValueError("Flow rate cannot be negative.")
#         return flowrate_cfs / 35.3147
# 
# 
# if __name__ == "__main__":
#     print(f"1000 psi = {psi_to_mpa(1000):.2f} MPa")
#     print(f"1000 MPa = {mpa_to_psi(1000):.2f} psi")
#     print(f"10 inches = {inches_to_mm(10):.2f} mm")
#     print(f"12 meters = {metres_to_feet(12):.2f} feet")
#     print(f"25°C = {celsius_to_fahrenheit(25):.2f}°F")
#     print(f"100°F = {fahrenheit_to_celsius(100):.2f}°C")
#     print(f"100 lbf = {lbf_to_newtons(100):.2f} N")
#     print(f"100 N = {newtons_to_lbf(100):.2f} lbf")
#     print(f"100 sq ft = {sq_feet_to_sq_meters(100):.2f} m²")
#     print(f"100 m² = {sq_meters_to_sq_feet(100):.2f} ft²")
#     print(f"100 cu m = {cubic_meters_to_cubic_feet(100):.2f} cu ft")
#     print(f"100 cu ft = {cubic_feet_to_cubic_meters(100):.2f} cu m")
#     print(f"100 kg = {kg_to_pounds(100):.2f} lbs")
#     print(f"100 lbs = {pounds_to_kg(100):.2f} kg")
#     print(f"100 cms = {cms_to_cfs(100):.2f} cfs")
#     print(f"100 cfs = {cfs_to_cms(100):.2f} cms")
# 
#